### PR TITLE
Unity 2017.1 compatible

### PR DESCRIPTION
**Pull request by HectorPulido**
Unity 2017.1 has a bug with WWW so I replaced it for UnityWebRequest

### CODE REVIEW

**Comment by ppz0th** [comment]
Thanks~, I'll review it soon :)

**Comment by smallmiro** [comment]
@HectorPulido  Please, before changes can be accepted a Contributor Licensing Agreement for Individual | Corporate must be completed

* If you are an individual writing original source code and you're sure you own the intellectual property, then you'll need to sign an [Individual CLA](https://docs.google.com/forms/d/1MhnsLF2VxhqnRp2fwifXxcpCsoa193T7RKthq4E9KEs/viewform?edit_requested=true)
* If you work for a company that wants to allow you to contribute your work, then you'll need to sign a [Corporate CLA](https://docs.google.com/forms/d/1z-TB_Q6ll7Q1-kft3gQp9mPdC1wfxDVP3u0_nyYJE9g/viewform?edit_requested=true)
* If you are an representative writing original source code, then you'll need to sign a [Representative CLA](https://docs.google.com/forms/d/14JqWub7w2Tw-LjBIs0viJFah5vwjRtNKCNhHz9Pnnpw/viewform?edit_requested=true)

Thank you your Contribute code!

**Comment by HectorPulido** [comment]
Done, I hope it help

**Comment by ppz0th** [comment]
@HectorPulido 
It's merged. This will be applied on the next release. thanks~

**Pull request merged**
